### ISSUE TITLE
Camera Orientation (Nexus 5X)

### ISSUE THREAD

**Issue by diemmarkus** [TUWien/DocScan#1]
@hollaus could you add the link please?

**Comment by hollaus** [comment]
camera in Nexus 5X is mounted 180 degrees (compared to other cameras):
https://www.reddit.com/r/Android/comments/3rjbo8/nexus5x_marshmallow_camera_problem/cwqzqgh
http://9to5google.com/2015/11/07/why-are-images-nexus-5x-upside-down/

**Comment by hollaus** [comment]
Works now on Nexus 5X.
The correct camera orientation is now calculated in CameraPreview.calculatePreviewOrientation.
This orientation is assigned to the camera and also to the screen coordinates conversion in CVResult.
