### ISSUE TITLE
Couldn't find "libdocscan-native.so"

### ISSUE THREAD

**Issue by ADTLabs** [TUWien/DocScan#12]
Process: at.ac.tuwien.caa.docscan, PID: 10261
                                                                          java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/at.ac.tuwien.caa.docscan-1/base.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_dependencies_apk.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_0_apk.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_1_apk.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_2_apk.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_3_apk.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_4_apk.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_5_apk.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_6_apk.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_7_apk.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_8_apk.apk", zip file "/data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/at.ac.tuwien.caa.docscan-1/lib/arm, /data/app/at.ac.tuwien.caa.docscan-1/base.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/at.ac.tuwien.caa.docscan-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libdocscan-native.so"

We have followed all the steps that you mentioned in order to make it work and found one issue now i.e "Couldn't find "libdocscan-native.so", please check this and advise if we are missing anything in provided steps.

**Comment by diemmarkus** [comment]
the dependency `libdocscan-native.so` you are missing should be built by android studio. Can you check if it was created or if there are any compile errors?
I am sure @hollaus can tell you more soon.

**Comment by hollaus** [comment]
I made a small correction in the app/build.gradle. Can you please pull the project and clean+rebuild? (Sorry for the late reply, I was on holiday.)
