### ISSUE TITLE
Installing the app - wrong answer

### ISSUE THREAD

**Issue by ElseG** [TUWien/DocScan#22]
When installing the app, one gets a question: May we use your data to give you relevant ads. I said no, where to the app answered "thank you for letting us give you relevant ads"!

**Comment by hollaus** [comment]
Our app contains no ads and also none of the messages that you described. Are you sure that you have installed the app belonging to this github repo?
https://play.google.com/store/apps/details?id=at.ac.tuwien.caa.docscan

**Comment by ElseG** [comment]
You are right - it seems that I have downloaded another app with the same name. I have now found the correct one. Thank you for your answer.

**Comment by hollaus** [comment]
Glad to hear that :smiley:
