### ISSUE TITLE
RuntimeException in DocumentViewerActivity

### ISSUE THREAD

**Issue by hollaus** [TUWien/DocScan#33]
In case the 'Don't keep activities' setting is enabled in the developer options, `DocumentViewerActivity` crashes in the following scenario:
- In`CameraActivity` open `PageSlideActivity`
- Click `All images`
- Open a page in the `DocumentViewerActivity`
- Press the back button in the `PageSlideActivity`.

This opens the `DocumentViewerActivity` where the following line leads to a RuntimeException:
https://github.com/TUWien/DocScan/blob/c9c6ab4d74e3f3538a872457aa3f8ad960974767/app/src/main/java/at/ac/tuwien/caa/docscan/ui/docviewer/DocumentViewerActivity.kt#L163

If the exception is caught, the Activity is correctly opened.

**Comment by matejbart** [comment]
Closing this issue ticket as it has been already fixed within #34
