### ISSUE TITLE
FocusMeasure

### ISSUE THREAD

**Issue by hollaus** [TUWien/DocScan#6]
On the Moto E and Samsung Galaxy Tab 10.1 the app crashes in the FocusMeasure.apply:

10-18 20:50:14.921 31078-31360/at.ac.tuwien.caa.docscan A/libc: invalid address or address of corrupt block 0xb92bc048 passed to dlfree
10-18 20:50:14.922 31078-31360/at.ac.tuwien.caa.docscan A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 31360 (Thread-4654)

Unfortunately, no more debug output is given in Android studio.

**Comment by flow79** [comment]
ptr issue (double instead of float)
should resolve the crashes - please check on Galaxy Tab/Moto E

**Comment by flow79** [comment]
checked
